### ISSUE TITLE
Question reg. URI scheme

### ISSUE THREAD

**Issue by LordMike** [LordMike/MBW.Tools.RabbitDump#4]
From Nuget, via mail.

Dear Mike,

Could you change the amqp URL format? If I do the following: amqp://user:password@host:post/vhost it looks for a vhost "/vhost". This is not correct and according to the specification in my opinion. (See: https://www.rabbitmq.com/uri-spec.html)

Correct would be: Use vhost "/" = amqp://user:password@host:post// Use vhost "/vhost" = amqp://user:password@host:post//vhost Use vhost "vhost" = amqp://user:password@host:post/vhost

It is now impossible to select a vhost without a leading "/".

Cheers, Steven

**Comment by LordMike** [comment]
I have only ever seen vhosts with a leading slash, but I suppose that any character will do, as it can simply be url-encoded.. 

Perhaps this.

* The URI scheme will be as you suggest, so to get `/vhost` you need to do `...//vhost` (we'll convert slashes for convenience, even if the spec says they should be url encoded)
* You can specify an vhost with a commandline, e.g. `--source-vhost blah` ... might not be necessary if we do the conversion from text to url-encoded (which is necessary pr what RabbitMQ writes)

**Comment by Edreih** [comment]
Hi there,
I'm facing the same issue... our vhosts are named without a `/` in front. 
As the tool stands currently, there is no way to target these vhost? 

Thanks,
Dre

**Comment by LordMike** [comment]
As this tool is now. No.

If you can, you can edit the code to f.ex. strip the leading slash.

**Comment by yassenb** [comment]
I don't see how you can claim that the tool's behaviour is correct. vhost-s without a leading `/` is obviously allowed and the `/` in the URI should obviously not be considered as part of the `vhost`. See the specification here: https://www.rabbitmq.com/uri-spec.html. The solution is simple - strip the leading character from `uri.AbsolutePath` here: https://github.com/LordMike/MBW.Tools.RabbitDump/blob/master/src/MBW.Tools.RabbitDump/Movers/Amqp/UriConnectionFactory.cs#L26

**Comment by LordMike** [comment]
Actually, it's a bit trickier than that. There's also some handling of encoded names, like %2F for /'s. The spec you linked says:

> The vhost is a single segment. Therefore, any "/" characters that appear in the vhost name must be percent-encoded. URIs with multi-segment paths do not obey this specification.

And:

> The vhost component may be absent; this is indicated by the lack of a "/" character following the amqp_authority. An absent vhost component is not equivalent to an empty (i.e. zero-length) vhost name. 

Which in principle means that this tool should fail, if the path is blank (no leading '/').

**Comment by mhsimkin** [comment]
Hi. On all our Rabbit Servers, the vhost names do not begin with slashes. It might make more sense to not have the vhost part of the URI and instead specify it with it's own command line parameter.
