### ISSUE TITLE
Doesn't work with non-default virtual host

### ISSUE THREAD

**Issue by yassenb** [LordMike/MBW.Tools.RabbitDump#5]
When specifying a virtual host in the AMQP URI the tool doesn't work because it takes the slash separator as part of the vhost name, i.e. `amqp://user:pass@host/vhost` tries to access the `/vhost` vhost and it should try `vhost` instead. I believe the problem is here: https://github.com/LordMike/MBW.Tools.RabbitDump/blob/master/src/MBW.Tools.RabbitDump/Movers/Amqp/UriConnectionFactory.cs#L26

**Comment by LordMike** [comment]
Yea, I've seen this before - I'm not sure how to resolve it (keeping the input as an URI).. 

See #4
